# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_books_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='users',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ManyToManyField(related_name='user', to='belt_app.Users'),
        ),
    ]
